<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Кредитование</title>
</head>
<body>

<form action="" method="post">

    <h4>Сумма кредита:</h4>
    <input type="text" name="sum" placeholder="Число в гривнах" value="<?= $_POST['sum']; ?>"/><br>

    <h4>Первоначальный взнос:</h4>
    <input type="text" name="firstPay" placeholder="В процентах" value="<?= $_POST['firstPay']; ?>"/><br>
    <h4>Срок кредитования:</h4>
    <input type="text" name="credit" placeholder="От 1 до 7 лет" value="<?= $_POST['credit']; ?>"/><br><br>


    <button class="btn btn-primary" type="submit">Посчитать</button>
</form>
<br>

<table border="1" cellpadding="5">
    <?php require "calculator.php"?>


</table>
</body>
</html>




